export const setType = (type) => ({type: 'products/type', payload: type})
export const setPage = (page) => ({type: 'products/page', payload: page})
export const setSort = (sort) => ({type: 'products/sort', payload: sort})
export const setLayout = (layout) => ({type: 'products/layout', payload: layout})
export const addLiked = (code) => ({type: 'liked/add', payload: code})
export const putProduct = (product) => ({type: 'product/put', payload: product})
export const increaseDownloaded = () => ({type: 'product/increaseDownloaded'})
export const increaseViewed = () => ({type: 'product/increaseViewed'})
export const increaseRating = (prop) => ({type: 'product/increaseRating', payload: prop})
export const putRatingComment = (ratingComment) => ({type: 'product/putRatingComment', payload: ratingComment})
export const postComment = (comment) => ({type: 'product/postComment', payload: comment})
export const reset = () => ({type: 'reset'})